CREATE TABLE IF NOT EXISTS "spicy_social_club_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "spicy_social_club_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" varchar(256),
	"comment" varchar(4096),
	"author_id" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "spicy_social_club_restaurant" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "spicy_social_club_restaurant_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256) NOT NULL,
	"address" varchar(256) NOT NULL,
	"description" varchar(256),
	"comments" jsonb DEFAULT '[]'::jsonb,
	"stats" jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "spicy_social_club_users" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "spicy_social_club_users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"accountName" varchar(20),
	"password" varchar(256) NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "title_idx" ON "spicy_social_club_post" USING btree ("title");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "author_idx" ON "spicy_social_club_post" USING btree ("author_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "restaurant_name_idx" ON "spicy_social_club_restaurant" USING btree ("name");